# Generated by Django 2.2.11 on 2020-04-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subrubric',
            options={'ordering': ('super_rubric__order', 'super_rubric__name', 'order', 'name'), 'verbose_name': 'Подрубрика тем', 'verbose_name_plural': 'Подрубрики тем'},
        ),
        migrations.AlterModelOptions(
            name='superrubric',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Надрубрика тем', 'verbose_name_plural': 'Надрубрики тем'},
        ),
    ]
