# Generated by Django 2.2.11 on 2020-03-23 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_projeсt'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeсt',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.SubRubric', verbose_name='Pyбpикa'),
        ),
    ]
