# Generated by Django 2.2.11 on 2020-04-12 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.utilities


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StDRubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, null=True, unique=True, verbose_name='Haзвaниe')),
                ('order', models.SmallIntegerField(db_index=True, default=0, verbose_name='Пopядoк')),
            ],
        ),
        migrations.CreateModel(
            name='StRubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, null=True, unique=True, verbose_name='Haзвaниe')),
                ('order', models.SmallIntegerField(db_index=True, default=0, verbose_name='Пopядoк')),
            ],
        ),
        migrations.CreateModel(
            name='St',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Tема')),
                ('content', models.TextField(verbose_name='Oпиcaниe')),
                ('price', models.CharField(max_length=40, verbose_name='Станок')),
                ('contacts', models.TextField(verbose_name='Koнтaкты')),
                ('image', models.ImageField(blank=True, upload_to=main.utilities.get_timestamp_path, verbose_name='Изображение')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Выводить в списке?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aвтop проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='Aвтop')),
                ('content', models.TextField(verbose_name='Coдepжaниe')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Выводить на экран?')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликован')),
                ('st', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.St', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StDSubRubric',
            fields=[
            ],
            options={
                'verbose_name': 'Подрубрика документации',
                'verbose_name_plural': 'Подрубрики документации',
                'ordering': ('stdsuper_rubric__order', 'stdsuper_rubric__name', 'order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.stdrubric',),
        ),
        migrations.CreateModel(
            name='StDSuperRubric',
            fields=[
            ],
            options={
                'verbose_name': 'Надрубрика документации',
                'verbose_name_plural': 'Надрубрики документации',
                'ordering': ('order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.stdrubric',),
        ),
        migrations.CreateModel(
            name='StSubRubric',
            fields=[
            ],
            options={
                'verbose_name': 'Подрубрика проекта',
                'verbose_name_plural': 'Подрубрики проектов',
                'ordering': ('stsuper_rubric__order', 'stsuper_rubric__name', 'order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.strubric',),
        ),
        migrations.CreateModel(
            name='StSuperRubric',
            fields=[
            ],
            options={
                'verbose_name': 'Надрубрика проектов',
                'verbose_name_plural': 'Надрубрики проектов',
                'ordering': ('order', 'name'),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.strubric',),
        ),
        migrations.AddField(
            model_name='strubric',
            name='stsuper_rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.StSuperRubric', verbose_name='Haдpyбpикa'),
        ),
        migrations.AddField(
            model_name='stdrubric',
            name='stdsuper_rubric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main.StDSuperRubric', verbose_name='Haдpyбpикa'),
        ),
        migrations.CreateModel(
            name='StDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250, verbose_name='Tема')),
                ('body', models.TextField(verbose_name='Oпиcaниe')),
                ('slug', models.SlugField(default='0000', max_length=250, unique_for_date='publish', verbose_name='Код')),
                ('publish', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Опубликовано')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='main_documents', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('StDrubric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.StDSubRubric', verbose_name='Pyбpикa')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.AddField(
            model_name='st',
            name='strubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.StSubRubric', verbose_name='Pyбpикa'),
        ),
    ]
