# Generated by Django 2.2.11 on 2020-04-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stdsubrubric',
            options={'ordering': ('stdsuper_rubric__order', 'stdsuper_rubric__name', 'order', 'name'), 'verbose_name': 'Подрубрика документации', 'verbose_name_plural': 'Подрубрики документации'},
        ),
        migrations.AlterModelOptions(
            name='stsubrubric',
            options={'ordering': ('stsuper_rubric__order', 'stsuper_rubric__name', 'order', 'name'), 'verbose_name': 'Подрубрика проекта', 'verbose_name_plural': 'Подрубрики проектов'},
        ),
    ]
