# Generated by Django 2.2.11 on 2020-04-15 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='st',
            name='image',
        ),
    ]
