# Generated by Django 2.2.11 on 2020-04-03 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='st',
            options={'ordering': ['-created_at'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='stdocument',
            name='body',
            field=models.TextField(default=1, verbose_name='Oпиcaниe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stdocument',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.SubRubric', verbose_name='Pyбpикa'),
        ),
        migrations.AlterField(
            model_name='st',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aвтop проекта'),
        ),
    ]
