# Generated by Django 2.2.11 on 2020-04-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200409_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stdsuperrubric',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Надрубрика документации', 'verbose_name_plural': 'Надрубрики документации'},
        ),
        migrations.AlterModelOptions(
            name='stsuperrubric',
            options={'ordering': ('order', 'name'), 'verbose_name': 'Надрубрика проектов', 'verbose_name_plural': 'Надрубрики проектов'},
        ),
    ]
